name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          source scripts/venv.rc

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest -vv --ignore=privatemode/document_store/test_hybrid_db.py --ignore=privatemode/document_store/fts_test.py  --ignore=tests/test_retrieval_query.py
